services:
  - type: web
    name: portfolio
    runtime: static
    plan: free
    branch: animation
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
